### ISSUE TITLE
Values don't appear when Label is changed for the dimension 

### ISSUE THREAD

**Issue by KA37PKV10** [ClimberAB/ClimberSelectionBar#47] opened 2017-12-06 16:32 UTC
I have the climber selection bar but the problem is when I am renaming the label of  the dimension it shows the values/fields of the dimension in the edit window but as soon as I go to the preview or over view , those values don't appear. And if I leave the dimension label as is, the values appear in preview or over view of the app.

### Steps to Reproduce

1. Took a direct dimension (Alphanumeric, Not Calculated)
2. Changed the label under dimension 
3. Show titles disabled 

##### Expected behavior

Give the dimension values with one value defaulted 

##### Actual behavior

The values of the dimension disappear once I come out of the edit window to Preview of the app!

### Environment
Enterprise

### Versions

* Extension version:
* Browser: Chrome
* Qlik Sense: 
* Operating system: MAC

**Comment by MichaelClimber** [comment] 2017-12-11 12:08
Hi,
we are not able to reproduce this behavior. Could you possible give us a few screen shots of what you are trying to do? Any errors in the console?

Kind regards

Michael

**Comment by edwardhallgren** [comment] 2018-03-11 13:15
Closing issue! Please reopen the issue if you still having problem and attached some screen shots.

Br
Edward

**Closed by edwardhallgren** 2018-03-11 13:15 UTC
