### ISSUE TITLE
Calendar is pinned to side of window

### ISSUE THREAD

**Issue by daniellecarrick** [ClimberAB/ClimberSelectionBar#42] opened 2017-11-10 19:37 UTC
### Description

After making an initial selection, the calendar disappears as expected but once the user scrolls down, they'll find the calendar was actually pinned just out of view on the bottom of the browser and half of it still appears on the left of the screen. 

### Steps to Reproduce

1. Make a selection
2. Scroll down page
3. Calendar is pinned on left side of the browser

##### Expected behavior

I expect the calendar to only be visible when making a selection.

##### Actual behavior

Calendar seems to disappear at first but in actuality is outside of window view until scrolling. Also, if a user selects the misplaced calendar, the "Apply" and "Cancel" buttons do not respond to mouse events.

### Environment
```
Macbook Pro Laptop. MacOS Sierra. Chrome.

```
### Versions

* Extension version: Latest
* Browser: Chrome
* Qlik Sense: September 2017 release
* Operating system: MacOS Sierra

### Screenshots

<img width="270" alt="screen shot 2017-11-10 at 2 29 06 pm" src="https://user-images.githubusercontent.com/2934190/32675312-7ee53308-c624-11e7-952c-3ec3973d4cbf.png">

**Comment by Ashfaq184** [comment] 2017-11-12 06:24
Hi,

Even I have the same issue. It was working fine with June, this issue comes with Sep 2017 Release.

Regards
ASHFAQ

**Comment by kfsjostrand** [comment] 2018-02-01 15:52
Try our latest release and see if the issue is fixed.
How are you able to scroll in Chrome? Are you using some other extensions, because scrolling is not available in Chrome, only in mobile mode.
Regards
Karl

**Comment by edwardhallgren** [comment] 2018-03-11 13:11
Closing issue. Please report again if you still having problem.

Br
Edward

**Closed by edwardhallgren** 2018-03-11 13:11 UTC
